### ISSUE TITLE
Join request: nc

### ISSUE THREAD

**Issue by neilco** [gofrs/join-requests#17]
Slack Display name: Neil Cowburn

Project(s) you're interested in helping with: Anything & everything where I can add value.

**Comment by theckman** [comment]
@neilco when you've a moment, would you be able to pop in to the #gofrs channel and link to this PR? It's a very manual validation step to ensure people are in the channel / match the Slack user to the PR.

**Comment by neilco** [comment]
@theckman Sure thing. It’s done. 👍

**Comment by theckman** [comment]
@neilco perfecto! I just sent the invite over your way. Please close this issue once you've had the chance to accept.
