### ISSUE TITLE
Join Request: vedhavyas

### ISSUE THREAD

**Issue by vedhavyas** [gofrs/join-requests#22]
Slack Display name: vedhavyas

Project(s) you're interested in helping with: Would love to help with any project

**Comment by theckman** [comment]
@vedhavyas invite sent your way. Please close this issue once you've been able to accept.

**Comment by theckman** [comment]
@vedhavyas have you been able to accept yet?

**Comment by vedhavyas** [comment]
@theckman yes. Thank you. Closing this now
