### ISSUE TITLE
Join request: alex.pliutau

### ISSUE THREAD

**Issue by plutov** [gofrs/join-requests#26]
Slack Display name: alex.pliutau

Project(s) you're interested in helping with: wit.ai Go packages, https://github.com/logpacker/PayPal-Go-SDK

**Comment by niaow** [comment]
@plutov help requests should be submitted to the help-requests repo: https://github.com/gofrs/help-requests/issues

**Comment by plutov** [comment]
It os a join request to help not with a specific packages but with all possible in org.

**Comment by theckman** [comment]
@plutov invite sent. Please close this issue when you've accepted it.

**Comment by theckman** [comment]
@plutov have you had the opportunity to accept the invite yet?

**Comment by plutov** [comment]
Accepted, thank you.
