### ISSUE TITLE
Join request: ferhatelmas

### ISSUE THREAD

**Issue by ferhatelmas** [gofrs/join-requests#28]
Slack Display name: **ferhatelmas**

Project(s) you're interested in helping with: *Anything*, preferably, common tooling for the organization.

**Comment by theckman** [comment]
@ferhatelmas thank you for your interest in joining! I've sent an invite your way; please close this issue once you've been able to accept it.

**Comment by ferhatelmas** [comment]
@theckman thanks, I'm in.
