### ISSUE TITLE
Join request: leighmcculloch

### ISSUE THREAD

**Issue by leighmcculloch** [gofrs/join-requests#29]
Slack Display name: `leighmcculloch`

Project(s) you're interested in helping with: `uuid`, any.

**Comment by theckman** [comment]
@leighmcculloch the invite was sent. Please close this issue when you've been able to accept it.

**Comment by leighmcculloch** [comment]
Thanks!

**Comment by leighmcculloch** [comment]
👋I'm not sure where to ask about this, so I'm posting this here since I just joined. I think the idea of us helping bring stability and maintain dormant code that's important to everyone is great. But I'm a little concerned about the way this community will be taking code in-house might have on open distributed development in the Go community. I think if we can find forks of unmaintained projects that are maintained and have a maintainer who wants to put the effort in, we should be rallying around those existing fork rather than stealing their potential lime light by creating an 'official' place for code to live. I had this thought when I saw @kevinburke's https://github.com/satori/go.uuid/issues/83#issuecomment-404874947 saying he has a fork of uuid at https://github.com/kevinburke/go.uuid and that he was committed to maintaining it. Instead of reforking satori/go.uuid, we could be rallying around @kevinburke and contributing to his, and by doing this building up the community that already exists. We could do the same for other projects too.

**Comment by kevinburke** [comment]
Hi Leigh,
I appreciate the nice comment. To be honest, forking that library was the best way to unblock myself for what I needed to get done. I don't plan on doing more (any?) contributions to the fork, as it's adequate for it's use and it doesn't seem like that will change if Go changes.

It seems like the contributors here are pretty happy with the uuid lib they created, and excited about it, and I think that's great!

**Comment by leighmcculloch** [comment]
Hooray! I read things into the [conversation I linked to](https://github.com/satori/go.uuid/issues/83#issuecomment-404874947) that just weren't there. Thanks for clearing that up @kevinburke. 🎉
