### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by yarbelk** [gofrs/join-requests#33]
Slack Display name:
James Rivett-Carnac
Project(s) you're interested in helping with:
I like contributing to documentation, testing and QoL improvements to projects; Want to help support the community driven libraries by helping with these things.

**Comment by theckman** [comment]
@yarbelk invite sent your way. Please close this issue when you've had a chance to accept it.

**Comment by theckman** [comment]
@yarbelk have you been able to accept yet?

**Comment by yarbelk** [comment]
@theckman yes!
