### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by mdanzinger** [gofrs/join-requests#44]
Slack Display name: mdanzinger

Project(s) you're interested in helping with: Any that fall within my skillset.

Other information: I'm more of a Jr when it comes to backend work, but I'd be happy to tackle any of the easier issues until I'm more competent and able to contribute in more meaningful ways. I have extensive experience working with websites, so most front-end related issues I should be able to work on.

If you're trying to keep this organization exclusive to more seasoned engineers, no worries at all!

**Comment by theckman** [comment]
@mdanzinger Sorry for the delay; late November and December were busy. Invite sent; please close this issue when you've accepted the invite. It helps us know which invites have been processed and which are outstanding.
