### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by albertorestifo** [gofrs/join-requests#45]
Slack Display name: arestifo

Project(s) you're interested in helping with: Any where I can help

I have been using go in production at my company for about 8 months now and I've been experimenting with go for the past year.

Most of my experience is with web services and micro services but I'd like to focus on more low-level libraries to improve my knowledge in that area.

I've been wanting to contribute to an open source project for a while, but having no idea which one to start with, I thought I might join this org an help.

**Comment by theckman** [comment]
@albertorestifo Sorry for the delay; late November and December were busy. Invite sent; please close this issue when you've accepted the invite. It helps us know which invites have been processed and which are outstanding.

**Comment by albertorestifo** [comment]
Thank you!
