### ISSUE TITLE
Join Request (Márk Sági-Kazár)

### ISSUE THREAD

**Issue by sagikazarmark** [gofrs/join-requests#48]
Slack Display name: Márk Sági-Kazár (mark.sagikazar)

Project(s) you're interested in helping with: I'm mostly concerned about DX and interfaces these days, so I'd be willing to work on projects involving any of these topics. I would also be happy to work on dep if that discussion gets resolved. Other current topics I'm working on these days: logging/error handling, distributed tracing, gRPC, Kubernetes.

Thinking of actual projects: I'm really interested in spf13/viper (https://github.com/gofrs/help-requests/issues/31). I already have quite a few contributions there and trying to actively help people on the issue tracker. I'm also interested in helping with logrus.

**Comment by theckman** [comment]
@sagikazarmark Invite sent; please close this issue when you've accepted the invite. It helps us know which invites have been processed and which are outstanding.

**Comment by sagikazarmark** [comment]
Thanks @theckman for the invitation!
