### ISSUE TITLE
Join Request: Ludovic Fernandez

### ISSUE THREAD

**Issue by ldez** [gofrs/join-requests#76]
Slack Display name:
Ludovic Fernandez

Project(s) you're interested in helping with:
- https://github.com/gofrs/flock

I'm the core maintainer of [lego](https://github.com/go-acme/lego), we depend on  `github.com/oracle/oci-go-sdk/v65` and this module depends on `github.com/gofrs/flock`.
On `lego` we have a problem with Solaris and flock.

I'm also a core maintainer of [golangci-lint](https://github.com/golangci/golangci-lint), we use directly `github.com/gofrs/flock` for our integration tests.

I have already been invited to the Slack channel by @cristaloleg

**Comment by cristaloleg** [comment]
@theckman @acln0

**Comment by dylan-bourque** [comment]
Invitation sent.  Please close this issue once you have accepted.

**Comment by ldez** [comment]
Thank you
